### ISSUE TITLE
Move away from the deprecated distutils.dir_util.copy_tree (copy_vault feature)

### ISSUE THREAD

**Issue by jcolson** [obsidian-html/obsidian-html#223]
```
> COPYING VAULT /Volumes/GoogleDrive/My Drive/Obsidian/Jay's Notebook TO /var/folders/5w/06lpntmj30sffnlm129dp7xc0000gp/T/tmpvihtkkei
	Will overwrite paths: obsidian_folder, obsidian_entrypoint
Traceback (most recent call last):
  File "/usr/local/bin/obsidianhtml", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/site-packages/obsidianhtml/__init__.py", line 521, in main
    tmpdir = CreateTemporaryCopy(source_folder_path=paths['obsidian_folder'], pb=pb)
  File "/usr/local/lib/python3.9/site-packages/obsidianhtml/lib.py", line 290, in CreateTemporaryCopy
    copytree(source_folder_path, tmpdir.name, dirs_exist_ok=True)
  File "/usr/local/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/shutil.py", line 566, in copytree
    return _copytree(entries=entries, src=src, dst=dst, symlinks=symlinks,
  File "/usr/local/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/shutil.py", line 522, in _copytree
    raise Error(errors)
shutil.Error: [("/Volumes/GoogleDrive/My Drive/Obsidian/Jay's Notebook/Personal/11-27-2011.md", '/var/folders/5w/06lpntmj30sffnlm129dp7xc0000gp/T/tmpvihtkkei/Personal/11-27-2011.md', "[Errno 1] Operation not permitted: '/var/folders/5w/06lpntmj30sffnlm129dp7xc0000gp/T/tmpvihtkkei/Personal/11-27-2011.md'"), ("/Volumes/GoogleDrive/My Drive/Obsidian/Jay's Notebook/Personal/TX-mailing-physical-address-c.md", '/var/folders/5w/06lpntmj30sffnlm129dp7xc0000gp/T/tmpvihtkkei/Personal/TX-mailing-physical-address-c.md', "[Errno 1] Operation not permitted: '/var/folders/5w/06lpntmj30sffnlm129dp7xc0000gp/T/tmpvihtkkei/Personal/TX-mailing-physical-address-c.md'"), ("/Volumes/GoogleDrive/My Drive/Obsidian/Jay's Notebook/Personal/tire-pressure.md", '/var/folders/5w/06lpntmj30sffnlm129dp7xc0000gp/T/tmpvihtkkei/Personal/tire-pressure.md', "[Errno 1] Operation not permitted: '/var/folders/5w/06lpntmj30sffnlm129dp7xc0000gp/T/tmpvihtkkei/Personal/tire-pressure.md'"), ("/Volumes/GoogleDrive/My Drive/Obsidian/Jay's Notebook/Personal/Chatting-with-sean.md", '/var/folders/5w/06lpntmj30sffnlm129dp7xc0000gp/T/tmpvihtkkei/Personal/Chatting-with-sean.md', "[Errno 1] Operation not permitted: '/var/folders/5w/06lpntmj30sffnlm129dp7xc0000gp/T/tmpvihtkkei/Personal/Chatting-with-sean.md'"), ("/Volumes/GoogleDrive/My Drive/Obsidian/Jay's Notebook/Personal/quasselcore-ssl-certificate-o.md", '/var/folders/5w/06lpntmj30sffnlm129dp7xc0000gp/T/tmpvihtkkei/Personal/quasselcore-ssl-certificate-o.md', "[Errno 1] Operation not permitted: '/var/folders/5w/06lpntmj30sffnlm129dp7xc0000gp/T/tmpvihtkkei/Personal/quasselcore-ssl-certificate-o.md'"), ("/Volumes/GoogleDrive/My Drive/Obsidian/Jay's Notebook/Personal/configure-apache-on-catalina.md", '/var/folders/5w/06lpntmj30sffnlm129dp7xc0000gp/T/tmpvihtkkei/Personal/configure-apache-on-catalina.md', "[Errno 1] Operation not permitted: '/var/folders/5w/06lpntmj30sffnlm129dp7xc0000gp/T/tmpvihtkkei/Personal/configure-apache-on-catalina.md'"), ("/Volumes/GoogleDrive/My Drive/Obsidian/Jay's Notebook/Personal/AWS---David-Brown.md", '/var/folders/5w/06lpntmj30sffnlm129dp7xc0000gp/T/tmpvihtkkei/Personal/AWS---David-Brown.md', "[Errno 1] Operation not permitted: '/var/folders/5w/06lpntmj30sffnlm129dp7xc0000gp/T/tmpvihtkkei/Personal/AWS---David-Brown.md'"), ("/Volumes/GoogleDrive/My Drive/Obsidian/Jay's Notebook/Personal/amazon---Tom-Hone---principal.md", '/var/folders/5w/06lpntmj30sffnlm129dp7xc0000gp/T/tmpvihtkkei/Personal/amazon---Tom-Hone---principal.md', "[Errno 1] Operation not permitted: '/var/folders/5w/06lpntmj30sffnlm129dp7xc0000gp/T/tmpvihtkkei/Personal/amazon---Tom-Hone---principal.md'"), ("/Volumes/GoogleDrive/My Drive/Obsidian/Jay's Notebook/Personal/learners-permit-requirements.md", '/var/folders/5w/06lpntmj30sffnlm129dp7xc0000gp/T/tmpvihtkkei/Personal/learners-permit-requirements.md', "[Errno 1] Operation not permitted: '/var/folders/5w/06lpntmj30sffnlm129dp7xc0000gp/T/tmpvihtkkei/Personal/learners-permit-requirements.md'"), ("/Volumes/GoogleDrive/My Drive/Obsidian/Jay's Notebook/Personal/Onenote-config.md", '/var/folders/5w/06lpntmj30sffnlm129dp7xc0000gp/T/tmpvihtkkei/Personal/Onenote-config.md', "[Errno 1] Operation not permitted: '/var/folders/5w/06lpntmj30sffnlm129dp7xc0000gp/T/tmpvihtkkei/Personal/Onenote-config.md'"), ("/Volumes/GoogleDrive/My Drive/Obsidian/Jay's Notebook/Personal/Majorca.md", '/var/folders/5w/06lpntmj30sffnlm129dp7xc0000gp/T/tmpvihtkkei/Personal/Majorca.md', "[Errno 1] Operation not permitted: '/var/folders/5w/06lpntmj30sffnlm129dp7xc0000gp/T/tmpvihtkkei/Personal/Majorca.md'"), ("/Volumes/GoogleDrive/My Drive/Obsidian/Jay's Notebook/Personal/Closet-spare-bedroom.md", '/var/folders/5w/06lpntmj30sffnlm129dp7xc0000gp/T/tmpvihtkkei/Personal/Closet-spare-bedroom.md', "[Errno 1] Operation not permitted: '/var/folders/5w/06lpntmj30sffnlm129dp7xc0000gp/T/tmpvihtkkei/Personal/Closet-spare-bedroom.md'"), ("/Volumes/GoogleDrive/My Drive/Obsidian/Jay's Notebook/Personal/Riley---politics---Feb-2,-202.md", '/var/folders/5w/06lpntmj30sffnlm129dp7xc0000gp/T/tmpvihtkkei/Personal/Riley---politics---Feb-2,-202.md', "[Errno 1] Operation not permitted: '/var/folders/5w/06lpntmj30sffnlm129dp7xc0000gp/T/tmpvihtkkei/Personal/Riley---politics---Feb-2,-202.md'"), ("/Volumes/GoogleDrive/My Drive/Obsidian/Jay's Notebook/Personal/place-in-florida-to-look-at-(.md", '/var/folders/5w/06lpntmj30sffnlm129dp7xc0000gp/T/tmpvihtkkei/Personal/place-in-florida-to-look-at-(.md', "[Errno 1] Operation not permitted: '/var/folders/5w/06lpntmj30sffnlm129dp7xc0000gp/T/tmpvihtkkei/Personal/place-in-florida-to-look-at-(.md'"), ("/Volumes/GoogleDrive/My Drive/Obsidian/Jay's Notebook/Personal/karmavpc-move---Dec-27,-2018.md", '/var/folders/5w/06lpntmj30sffnlm129dp7xc0000gp/T/tmpvihtkkei/Personal/karmavpc-move---Dec-27,-2018.md', "[Errno 1] Operation not permitted: '/var/folders/5w/06lpntmj30sffnlm129dp7xc0000gp/T/tmpvihtkkei/Personal/karmavpc-move---Dec-27,-2018.md'"), ("/Volumes/GoogleDrive/My Drive/Obsidian/Jay's Notebook/Personal/bord-gais---sseairtricity---g.md", '/var/folders/5w/06lpntmj30sffnlm129dp7xc0000gp/T/tmpvihtkkei/Personal/bord-gais---sseairtricity---g.md', "[Errno 1] Operation not permitted: '/var/folders/5w/06lpntmj30sffnlm129dp7xc0000gp/T/tmpvihtkkei/Personal/bord-gais---sseairtricity---g.md'"), ("/Volumes/GoogleDrive/My Drive/Obsidian/Jay's Notebook/Personal/google---anne-lise---Apr-22,-.md", '/var/folders/5w/06lpntmj30sffnlm129dp7xc0000gp/T/tmpvihtkkei/Personal/google---anne-lise---Apr-22,-.md', "[Errno 1] Operation not permitted: '/var/folders/5w/06lpntmj30sffnlm129dp7xc0000gp/T/tmpvihtkkei/Personal/google---anne-lise---Apr-22,-.md'"), ("/Volumes/GoogleDrive/My Drive/Obsidian/Jay's Notebook/Personal/Export-gpg-subkey-for-ssh.md", '/var/folders/5w/06lpntmj30sffnlm129dp7xc0000gp/T/tmpvihtkkei/Personal/Export-gpg-subkey-for-ssh.md', "[Errno 1] Operation not permitted: '/var/folders/5w/06lpntmj30sffnlm129dp7xc0000gp/T/tmpvihtkkei/Personal/Export-gpg-subkey-for-ssh.md'"), ("/Volumes/GoogleDrive
...
```

**Comment by dwrolvink** [comment]
I recently moved from distutils.dir_util copy_tree to shutil copytree, because python complains that the former is deprecated. I restored the old code, can you try it again?

Clearly I had no issues with it on Linux, but I'm guessing that this is the culprit on mac. Not sure what is going wrong here though. I'll have to look deeper in to it, maybe there are other alternatives.

Note that since I last spoke to you, there have been some major layout changes in the default html output, since you use custom css there might be some work involved in getting it working with the new output. See also the docs website for more information.

**Comment by jcolson** [comment]
that solved the "operation not permitted" issue ... 

yeah, my css is totally borked ... ;-)  i'll take a look at that later

**Comment by dwrolvink** [comment]
@jcolson I went back to shutil, but I got the advice to use shutil.copy() instead of the default shutil.copy2() as the copy-file function. There was also the advice to just copy the function over and edit it where necessary, so I did both.

I've added in a tad bit more logging. Can you try the current master again and give feedback?
For reference, the curent implementation now lives here: https://github.com/obsidian-html/obsidian-html/blob/e59387067c7c13bb9ae6aff1eaeec40187e61c30/obsidianhtml/lib.py#L300

**Comment by dwrolvink** [comment]
It's probably the copystats part that gives the issues, not the file copying itself. It was also suggested that this vague error arises in many cases when copying between different filesystems (like from ntfs to ext3). Is that happening in your setup?

**Comment by jcolson** [comment]
pulled latest master and tested the run ... looks like the copy works with no errors now.

i did notice, the first time I load the page (no cache) i get a pretty long loadtime for unpkg.com ... subsequent loads are fine.
<img width="620" alt="image" src="https://user-images.githubusercontent.com/2362647/165281897-5511a899-692f-4ba4-94a9-1b4fbc93131e.png">

all looks like it's working

**Comment by dwrolvink** [comment]
Is that an issue? Is that 700 miliseconds?

I had started to write a few lines of code to package it with the html output, but then I was like, this can be annoying for people behind a proxy / other internet weirdness, and I kind of like that the whole package is contained and doesn't make contact with other sources outside of the pip installs. Then I thought of just updating the code with each new build, but I don't like people having to upgrade because of an outdated hard-baked dependency if otherwise it works for them. 

So little gain in what might as well have been a hiccup at the pypi side of things I think.

**Comment by jcolson** [comment]
I think it was 7 seconds ...  It was probably an anomaly if you've never noticed it ... I wouldn't worry about it

**Comment by dwrolvink** [comment]
Yeah, I have it cached half of the time of course, but we'll keep an eye out for it if any other people have issues with it.
Closing as the copy part is done.
