### ISSUE TITLE
[Error] Updated to new version

### ISSUE THREAD

**Issue by dr-code** [obsidian-html/obsidian-html#265]
I'm getting this error after upgrading to the new version:

```
Traceback (most recent call last):
  File "/opt/homebrew/bin/obsidianhtml", line 8, in <module>
    sys.exit(main())
  File "/opt/homebrew/lib/python3.9/site-packages/obsidianhtml/__init__.py", line 662, in main
    recurseObisidianToMarkdown(ep, pb)
  File "/opt/homebrew/lib/python3.9/site-packages/obsidianhtml/__init__.py", line 97, in recurseObisidianToMarkdown
    recurseObisidianToMarkdown(lo, pb, log_level=log_level)
  File "/opt/homebrew/lib/python3.9/site-packages/obsidianhtml/__init__.py", line 97, in recurseObisidianToMarkdown
    recurseObisidianToMarkdown(lo, pb, log_level=log_level)
  File "/opt/homebrew/lib/python3.9/site-packages/obsidianhtml/__init__.py", line 97, in recurseObisidianToMarkdown
    recurseObisidianToMarkdown(lo, pb, log_level=log_level)
  File "/opt/homebrew/lib/python3.9/site-packages/obsidianhtml/__init__.py", line 56, in recurseObisidianToMarkdown
    md = MarkdownPage(pb, fo, 'note', files)
  File "/opt/homebrew/lib/python3.9/site-packages/obsidianhtml/MarkdownPage.py", line 44, in __init__
    self.metadata, self.page = frontmatter.parse(f.read())
  File "/opt/homebrew/lib/python3.9/site-packages/frontmatter/__init__.py", line 82, in parse
    fm = handler.load(fm)
  File "/opt/homebrew/lib/python3.9/site-packages/frontmatter/default_handlers.py", line 238, in load
    return yaml.load(fm, **kwargs)
  File "/opt/homebrew/lib/python3.9/site-packages/yaml/__init__.py", line 81, in load
    return loader.get_single_data()
  File "/opt/homebrew/lib/python3.9/site-packages/yaml/constructor.py", line 49, in get_single_data
    node = self.get_single_node()
  File "yaml/_yaml.pyx", line 673, in yaml._yaml.CParser.get_single_node
  File "yaml/_yaml.pyx", line 687, in yaml._yaml.CParser._compose_document
  File "yaml/_yaml.pyx", line 731, in yaml._yaml.CParser._compose_node
  File "yaml/_yaml.pyx", line 847, in yaml._yaml.CParser._compose_mapping_node
  File "yaml/_yaml.pyx", line 860, in yaml._yaml.CParser._parse_next_event
yaml.scanner.ScannerError: while scanning a simple key
  in "<unicode string>", line 3, column 1
could not find expected ':'
  in "<unicode string>", line 4, column 1
```

I uninstalled and re-installed 2.3.1 and still getting this. not sure where to go from here.

**Comment by dwrolvink** [comment]
The error is happening when it's parsing the frontmatter yaml on a note. 

Can you run it in verbose mode? Then you'll see what note this is happening on. If you have yaml in that note look if there is something weird going on with it.

Please also share the note (or just the front matter) here

**Comment by dr-code** [comment]
I fixed it.

I had a plugin regarding breadcrumbs in obsidian, but that didn't work well with obsidianhtml. I have gotten rid of it for now. 

Thanks!

**Comment by dwrolvink** [comment]
If you give an example of the frontmatter that that plugin generates then we can make it work. I'll close this issue for now, let me know if you want to work on getting it supported.
