### ISSUE TITLE
Improve path resolution when exporting inside of vault

### ISSUE THREAD

**Issue by dwrolvink** [obsidian-html/obsidian-html#332]
Some users like to export their md/html inside of their vault.
I wouldn't recommend this practice, but the fact is that this actually doesn't work,  where with the new pathbased indexing, it should work.
This points to hidden bugs with the path parsing system.

Example:
``` bash
git clone git@github.com:obsidian-html/obsidian-html.git
cd obsidian-html
mkdir local_configs
vim local_configs/test_vault.yml
```
``` yml
# local_configs/test_vault.yml
obsidian_folder_path_str: 'ci/test_vault/'
obsidian_entrypoint_path_str: 'ci/test_vault/entrypoint.md'
md_folder_path_str:  'ci/test_vault/md'
md_entrypoint_path_str: 'ci/test_vault/md/index.md'
html_output_folder_path_str: 'ci/test_vault/html'
``` 
First run works as intended
On second run though:
```
$ obsidianhtml -i local_configs/test_vault.yml                                                                              
> COPYING VAULT /home/user/git/obsidian-html/ci/test_vault TO /tmp/tmph92su5qe
< COPYING VAULT: Done
> CLEARING OUTPUT FOLDERS
> CREATING OUTPUT FOLDERS
> COMPILING MARKDOWN FROM OBSIDIAN CODE (/tmp/tmph92su5qe/entrypoint.md)
> COMPILING HTML FROM MARKDOWN CODE (/home/user/git/obsidian-html/ci/test_vault/md/index.md)
index.md
Traceback (most recent call last):
  File "/home/user/.local/bin/obsidianhtml", line 8, in <module>
    sys.exit(main())
  File "/home/user/.local/lib/python3.10/site-packages/obsidianhtml/__init__.py", line 755, in main
    ConvertMarkdownPageToHtmlPage(ep, pb)
  File "/home/user/.local/lib/python3.10/site-packages/obsidianhtml/__init__.py", line 396, in ConvertMarkdownPageToHtmlPage
    ConvertMarkdownPageToHtmlPage(lo, pb, backlinkNode, log_level=log_level)
  File "/home/user/.local/lib/python3.10/site-packages/obsidianhtml/__init__.py", line 396, in ConvertMarkdownPageToHtmlPage
    ConvertMarkdownPageToHtmlPage(lo, pb, backlinkNode, log_level=log_level)
  File "/home/user/.local/lib/python3.10/site-packages/obsidianhtml/__init__.py", line 396, in ConvertMarkdownPageToHtmlPage
    ConvertMarkdownPageToHtmlPage(lo, pb, backlinkNode, log_level=log_level)
  [Previous line repeated 5 more times]
  File "/home/user/.local/lib/python3.10/site-packages/obsidianhtml/__init__.py", line 247, in ConvertMarkdownPageToHtmlPage
    lo.copy_file('mth')
  File "/home/user/.local/lib/python3.10/site-packages/obsidianhtml/PathFinder.py", line 237, in copy_file
    shutil.copyfile(src_file_path, dst_file_path)
  File "/usr/lib/python3.10/shutil.py", line 254, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: '/home/user/git/obsidian-html/ci/test_vault/md/video/mp4/reaction_Objection_birb.mp4'
```

Which is correct, the file is present on the first run, absent when the second is done. 
Other files are present on the second run though.

Clearly something is going awry with the indexing.

**Comment by dwrolvink** [comment]
Removing the 
```
html_output_folder_path_str: 'ci/test_vault/html'
md_folder_path_str:  'ci/test_vault/md'
```
folders makes the run work again for 1 run, and one run only

**Comment by dwrolvink** [comment]
When running with verbose mode it gives stuff like 
```
found link /tmp/tmp6iwjtlur/Images.md (through parent /tmp/tmp6iwjtlur/md/md/md/excluded/rss_exclude.md)
```
Which is related to the issue here https://github.com/obsidian-html/obsidian-html/issues/271#issuecomment-1209954745

**Comment by dwrolvink** [comment]
So when a link like [[rss_index]] is found,  obsidianhtml tries to decide which from this list to pick:
```
['rss/rss_index.md', 'md/md/md/md/md/md/rss/rss_index.md']
```
The bug here is that is should pick the shortest path, but it returns the longest.

n.b. the obvious fix is to add the following to test_vault.yml:
```
exclude_subfolders:
  - ".obsidian"
  - ".trash"
  - ".DS_Store"
  - ".git"
  - "html"
  - "md"
```

See the bottom two lines. This will exclude them from being parsed as a part of the vault

**Comment by dwrolvink** [comment]
works now for me. It just returns the shortest found path. If this causes issues then we will have this issue as a counter example and then we can get to a better algorithm to find the correct paths.
