### ISSUE TITLE
Add current-state/note info to exceptions

### ISSUE THREAD

**Issue by dwrolvink** [obsidian-html/obsidian-html#351]
- Add a state object that can be passed around, containing information such as the type of operation and the note/link/etc being processed
- Edit the existing `raise` statements to include this information.
- See if it possible to edit default error raising to print out this information whenever an error occurs, even if it is outside of a `raise` statement.

**Comment by dwrolvink** [comment]
Alright, very basic error addendum has been added for a couple function calls.

Adding faulty yaml that cannot be parsed by frontmatter used to give this error:

```
Will delete previous output:
> COPYING VAULT /home/user/git/obsidian-html.github.io/__src/vault TO /tmp/tmpat758hzz
< COPYING VAULT: Done
> CREATING OUTPUT FOLDERS
> COMPILING MARKDOWN FROM OBSIDIAN CODE (/tmp/tmpat758hzz/ObsidianHtml.md)
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/user/git/obsidian-html/obsidianhtml/__main__.py", line 3, in <module>
    main()
  File "/home/user/git/obsidian-html/obsidianhtml/__init__.py", line 721, in main
    recurseObisidianToMarkdown(ep, pb)
  File "/home/user/git/obsidian-html/obsidianhtml/__init__.py", line 55, in recurseObisidianToMarkdown
    md = MarkdownPage(pb, fo, 'note', files)
  File "/home/user/git/obsidian-html/obsidianhtml/MarkdownPage.py", line 45, in __init__
    self.metadata, self.page = frontmatter.parse(f.read())
  File "/home/user/.local/lib/python3.10/site-packages/frontmatter/__init__.py", line 82, in parse
    fm = handler.load(fm)
  File "/home/user/.local/lib/python3.10/site-packages/frontmatter/default_handlers.py", line 238, in load
    return yaml.load(fm, **kwargs)
  File "/usr/lib/python3.10/site-packages/yaml/__init__.py", line 81, in load
    return loader.get_single_data()
  File "/usr/lib/python3.10/site-packages/yaml/constructor.py", line 49, in get_single_data
    node = self.get_single_node()
  File "yaml/_yaml.pyx", line 673, in yaml._yaml.CParser.get_single_node
  File "yaml/_yaml.pyx", line 687, in yaml._yaml.CParser._compose_document
  File "yaml/_yaml.pyx", line 731, in yaml._yaml.CParser._compose_node
  File "yaml/_yaml.pyx", line 845, in yaml._yaml.CParser._compose_mapping_node
  File "yaml/_yaml.pyx", line 729, in yaml._yaml.CParser._compose_node
  File "yaml/_yaml.pyx", line 806, in yaml._yaml.CParser._compose_sequence_node
  File "yaml/_yaml.pyx", line 731, in yaml._yaml.CParser._compose_node
  File "yaml/_yaml.pyx", line 845, in yaml._yaml.CParser._compose_mapping_node
  File "yaml/_yaml.pyx", line 694, in yaml._yaml.CParser._compose_node
  File "yaml/_yaml.pyx", line 860, in yaml._yaml.CParser._parse_next_event
yaml.scanner.ScannerError: while scanning for the next token
found character that cannot start any token
  in "<unicode string>", line 6, column 1
Python script failed. Exited.
```

Now gives:

```
Will delete previous output:
> COPYING VAULT /home/user/git/obsidian-html.github.io/__src/vault TO /tmp/tmp4ypyagsw
< COPYING VAULT: Done
> CREATING OUTPUT FOLDERS
> COMPILING MARKDOWN FROM OBSIDIAN CODE (/tmp/tmp4ypyagsw/ObsidianHtml.md)
Traceback (most recent call last):
  File "/home/user/git/obsidian-html/obsidianhtml/ErrorHandling.py", line 48, in _decorator
    res = f(*args, **kwargs)
  File "/home/user/git/obsidian-html/obsidianhtml/__init__.py", line 56, in recurseObisidianToMarkdown
    md = MarkdownPage(pb, fo, 'note', files)
  File "/home/user/git/obsidian-html/obsidianhtml/MarkdownPage.py", line 45, in __init__
    self.metadata, self.page = frontmatter.parse(f.read())
  File "/home/user/.local/lib/python3.10/site-packages/frontmatter/__init__.py", line 82, in parse
    fm = handler.load(fm)
  File "/home/user/.local/lib/python3.10/site-packages/frontmatter/default_handlers.py", line 238, in load
    return yaml.load(fm, **kwargs)
  File "/usr/lib/python3.10/site-packages/yaml/__init__.py", line 81, in load
    return loader.get_single_data()
  File "/usr/lib/python3.10/site-packages/yaml/constructor.py", line 49, in get_single_data
    node = self.get_single_node()
  File "yaml/_yaml.pyx", line 673, in yaml._yaml.CParser.get_single_node
  File "yaml/_yaml.pyx", line 687, in yaml._yaml.CParser._compose_document
  File "yaml/_yaml.pyx", line 731, in yaml._yaml.CParser._compose_node
  File "yaml/_yaml.pyx", line 845, in yaml._yaml.CParser._compose_mapping_node
  File "yaml/_yaml.pyx", line 729, in yaml._yaml.CParser._compose_node
  File "yaml/_yaml.pyx", line 806, in yaml._yaml.CParser._compose_sequence_node
  File "yaml/_yaml.pyx", line 731, in yaml._yaml.CParser._compose_node
  File "yaml/_yaml.pyx", line 845, in yaml._yaml.CParser._compose_mapping_node
  File "yaml/_yaml.pyx", line 694, in yaml._yaml.CParser._compose_node
  File "yaml/_yaml.pyx", line 860, in yaml._yaml.CParser._parse_next_event
yaml.scanner.ScannerError: while scanning for the next token
found character that cannot start any token
  in "<unicode string>", line 6, column 1

        OBS.HTML EXTRA ERROR INFORMATION:
        ---------------------------------
        Current action              : Conversion of Obsidian notes to proper Markdown notes
        Subroutine                  : recurseObisidianToMarkdown
        Current note being processed: /tmp/tmp4ypyagsw/ObsidianHtml.md
```


Perhaps next step is to add extra error info for specific links,  so you know for example which link on a page gives an issue, but I'm finding it hard to create errors all of a sudden so I'll just add that progressively as errors are found.
