### ISSUE TITLE
NameError: name 'warnings' is not defined

### ISSUE THREAD

**Issue by jcolson** [obsidian-html/obsidian-html#38]
```
File /Users/jcolson/src/personal/DragonHearts/output/md/media/Personal-Recipe--How-to-Make-Jalapeño-Pickles---Field-&-Stream-image3.gif not located, so not copied.
Traceback (most recent call last):
  File "/usr/local/bin/obsidianhtml", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/site-packages/obsidianhtml/__init__.py", line 532, in main
    ConvertMarkdownPageToHtmlPage(unparsed[k]['fullpath'], pb)
  File "/usr/local/lib/python3.9/site-packages/obsidianhtml/__init__.py", line 154, in ConvertMarkdownPageToHtmlPage
    warnings.warn(f"Image {str(full_link_path)} treated as external and not imported in html")
NameError: name 'warnings' is not defined
```

**Comment by dwrolvink** [comment]
I've added an external image to the example website so it will be added in testing rounds from now on :+1:
