### ISSUE TITLE
Add globbing/wildcards for excluded paths

### ISSUE THREAD

**Issue by atomicbird** [obsidian-html/obsidian-html#436]
Following on from [a discussion on excluding paths from the index](https://github.com/obsidian-html/obsidian-html/discussions/435), it would be really useful to have wildcards or globbing for excluded subfolders and possibly other paths. The motivation here is simply that I have multiple `assets` folders at different levels of my vault's hierarchy, and I'd like to include them all in `toggles/features/create_index_from_dir_structure/exclude_subfolders`. Right now I can list them all individually, and so far there are only seven, but it'd be an improvement to be able to exclude all `assets` folders at any hierarchy level with something like `*/assets` (or whatever syntax seems best there).

**Comment by dwrolvink** [comment]
https://obsidian-html.github.io/Configurations/Create%20Index%20from%20Directory%20Structure.html#!glob-patterns

Should "just work" now. 
Note that you need to install the latest master version for this to work atm: https://obsidian-html.github.io/Instructions/Install%20a%20different%20version.html#!install-master-branch

This addition will be released in v3.3.0

**Comment by atomicbird** [comment]
Installing from the latest is failing with an error about not finding `root_dir`:

    File "/usr/local/lib/python3.9/site-packages/obsidianhtml/CreateIndexFromDirStructure.py", line 50, in build_exclude_list
    exclude_folders += glob.glob(line, root_dir=self.root, recursive=True)
    TypeError: glob() got an unexpected keyword argument 'root_dir'

Here's the full log in case more detail is useful:

```
tph@neutrino (main)> obsidianhtml run -i obsidianhtml-config.yaml --clean
INFO: Config var was set. (provided by user through config file)
	obsidian_entrypoint_path_str: /Users/tph/Library/Mobile Documents/iCloud~md~obsidian/Documents/Family History wiki/index.md
INFO: Config var was set. (deduced)
	obsidian_folder_path_str: /Users/tph/Library/Mobile Documents/iCloud~md~obsidian/Documents/Family History wiki
INFO: Output folder path (/private/tmp/output/md) already exists, removing (due to --clean being set)
shutil.rmtree('/private/tmp/output/md')
INFO: Config var was set. (default behavior)
	md_folder_path_str: /private/tmp/output/md
INFO: Config var was set. (provided by user through config file)
	md_entrypoint_path_str: /tmp/output/md/index.md
INFO: Output folder path (/private/tmp/output/html/family-notebook/family-notebook) already exists, removing (due to --clean being set)
shutil.rmtree('/private/tmp/output/html/family-notebook/family-notebook')
INFO: Config var was set. (default behavior)
	html_output_folder_path_str: /private/tmp/output/html/family-notebook/family-notebook
> COPYING VAULT /Users/tph/Library/Mobile Documents/iCloud~md~obsidian/Documents/Family History wiki TO /var/folders/g5/48d2vfdd72n5rjz9rgtpxqvr0000gn/T/tmpyxegrc37
running: 
	 rsync -a /Users/tph/Library/Mobile Documents/iCloud~md~obsidian/Documents/Family History wiki/ /var/folders/g5/48d2vfdd72n5rjz9rgtpxqvr0000gn/T/tmpyxegrc37 --exclude /.obsidian/ --exclude /.trash/ --exclude /.DS_Store/ --exclude /.git/ --exclude /@templates/ --exclude /meta/
Copy succeeded 0  b''
< COPYING VAULT: Done
> CLEARING OUTPUT FOLDERS
> CREATING OUTPUT FOLDERS
> COMPILING MARKDOWN FROM OBSIDIAN CODE (/private/var/folders/g5/48d2vfdd72n5rjz9rgtpxqvr0000gn/T/tmpyxegrc37/index.md)
	> FEATURE: PROCESS ALL
	< FEATURE: PROCESS ALL: Done
> COMPILING HTML FROM MARKDOWN CODE (/private/tmp/output/md/index.md)
		 File /obs.html/tags/index.html not located, so not copied. @ /private/var/folders/g5/48d2vfdd72n5rjz9rgtpxqvr0000gn/T/tmpyxegrc37/index.md
	> FEATURE: PROCESS ALL
	< FEATURE: PROCESS ALL: Done
	> COMPILING INDEX FROM DIR STRUCTURE (/private/tmp/output/html/family-notebook/family-notebook/obs.html/dir_index.html)
Traceback (most recent call last):
  File "/usr/local/bin/obsidianhtml", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/site-packages/obsidianhtml/__init__.py", line 34, in main
    Run()
  File "/usr/local/lib/python3.9/site-packages/obsidianhtml/Run.py", line 181, in Run
    ConvertVault(config_save_path.as_posix())
  File "/usr/local/lib/python3.9/site-packages/obsidianhtml/ConvertVault.py", line 380, in ConvertVault
    pb.EnsureTreeObj()
  File "/usr/local/lib/python3.9/site-packages/obsidianhtml/PicknickBasket.py", line 65, in EnsureTreeObj
    self.treeobj = CreateIndexFromDirStructure(self, self.paths['html_output_folder'])
  File "/usr/local/lib/python3.9/site-packages/obsidianhtml/CreateIndexFromDirStructure.py", line 18, in __init__
    self.build_exclude_list()
  File "/usr/local/lib/python3.9/site-packages/obsidianhtml/CreateIndexFromDirStructure.py", line 50, in build_exclude_list
    exclude_folders += glob.glob(line, root_dir=self.root, recursive=True)
TypeError: glob() got an unexpected keyword argument 'root_dir'
```

**Comment by dwrolvink** [comment]
Oh.. root_dir was only added in python 3.10, not yet in 3.9
My bad, python3.9 should be supported at a minimum, so I will have to rework this.

**Comment by dwrolvink** [comment]
Alright that should work now if you fetch the latest code.

**Comment by atomicbird** [comment]
Looks good, thank you so much
