### ISSUE TITLE
Empty embed links are unhandled

### ISSUE THREAD

**Issue by Programmerino** [obsidian-html/obsidian-html#536]
The latest commit (94415cd4fc41c45779747da85a1d460127a58fc6) seems to have made empty embed links (e.g. `![[]]`) crash the program:

```
> COMPILING MARKDOWN FROM OBSIDIAN CODE (/tmp/tmp7mhc5ct6/file.md)
Traceback (most recent call last):
  File "/nix/store/yrx2yl0r4zbhapqbnwb5y98mlbgk678g-obsidianhtml-3.3.1/lib/python3.10/site-packages/obsidianhtml/core/ErrorHandling.py", line 60, in _decorator
    res = f(*args, **kwargs)
  File "/nix/store/yrx2yl0r4zbhapqbnwb5y98mlbgk678g-obsidianhtml-3.3.1/lib/python3.10/site-packages/obsidianhtml/controller/ConvertVault.py", line 526, in crawl_obsidian_notes_and_convert_to_markdown
    md.ConvertObsidianPageToMarkdownPage()
  File "/nix/store/yrx2yl0r4zbhapqbnwb5y98mlbgk678g-obsidianhtml-3.3.1/lib/python3.10/site-packages/obsidianhtml/parser/MarkdownPage.py", line 466, in ConvertObsidianPageToMarkdownPage
    result = GetObsidianFilePath(link, self.file_tree, self.pb)
  File "/nix/store/yrx2yl0r4zbhapqbnwb5y98mlbgk678g-obsidianhtml-3.3.1/lib/python3.10/site-packages/obsidianhtml/core/FileFinder.py", line 24, in GetObsidianFilePath
    output['rtr_path_str'], output['fo'] = FindFile(file_tree, link, pb)
  File "/nix/store/yrx2yl0r4zbhapqbnwb5y98mlbgk678g-obsidianhtml-3.3.1/lib/python3.10/site-packages/obsidianhtml/core/FileFinder.py", line 41, in FindFile
    if link[0] == '/':
IndexError: string index out of range

	OBS.HTML EXTRA ERROR INFORMATION:
	---------------------------------
	Current action              : Conversion of Obsidian notes to proper Markdown notes
	Subroutine                  : crawl_obsidian_notes_and_convert_to_markdown
	Current note being processed: /tmp/tmp7mhc5ct6/file.md (/tmp/test/test/file.md)
```

`file.md` just contains `![[]]`

**Comment by dwrolvink** [comment]
Should be fixed by this change. Let me know if there are still issues
