### ISSUE TITLE
Error when processing Mermaid

### ISSUE THREAD

**Issue by MShields1986** [obsidian-html/obsidian-html#557]
Just ran into this.

Error appears to be in the [MermaidExtension.py](https://github.com/obsidian-html/obsidian-html/blob/master/obsidianhtml/markdown_extensions/MermaidExtension.py)

Output and traceback:
```bash
> COPYING VAULT /home/matthew/Desktop/PhD/phd_notes/PhD TO /tmp/tmp5uu80cmf
< COPYING VAULT: Done
> CLEARING OUTPUT FOLDERS
> CREATING OUTPUT FOLDERS
> COMPILING MARKDOWN FROM OBSIDIAN CODE (/tmp/tmp5uu80cmf/Home.md)
> COMPILING HTML FROM MARKDOWN CODE (/home/matthew/Desktop/PhD/phd_notes/output/md/index.md)
Traceback (most recent call last):
  File "/home/matthew/.local/bin/obsidianhtml", line 8, in <module>
    sys.exit(main())
  File "/home/matthew/.local/lib/python3.9/site-packages/obsidianhtml/__init__.py", line 645, in main
    ConvertMarkdownPageToHtmlPage(ep, pb)
  File "/home/matthew/.local/lib/python3.9/site-packages/obsidianhtml/__init__.py", line 336, in ConvertMarkdownPageToHtmlPage
    ConvertMarkdownPageToHtmlPage(lo, pb, backlinkNode, log_level=log_level)
  File "/home/matthew/.local/lib/python3.9/site-packages/obsidianhtml/__init__.py", line 336, in ConvertMarkdownPageToHtmlPage
    ConvertMarkdownPageToHtmlPage(lo, pb, backlinkNode, log_level=log_level)
  File "/home/matthew/.local/lib/python3.9/site-packages/obsidianhtml/__init__.py", line 261, in ConvertMarkdownPageToHtmlPage
    html_body = markdown.markdown(md.page, extensions=['extra', 'codehilite', 'toc', 'obsidianhtml_md_mermaid_fork'], extension_configs=extension_configs)
  File "/home/matthew/.local/lib/python3.9/site-packages/markdown/core.py", line 387, in markdown
    return md.convert(text)
  File "/home/matthew/.local/lib/python3.9/site-packages/markdown/core.py", line 261, in convert
    self.lines = prep.run(self.lines)
  File "/home/matthew/.local/lib/python3.9/site-packages/obsidianhtml_md_mermaid_fork.py", line 47, in run
    if not re.match(r"^[\ \t]*$", old_line):
UnboundLocalError: local variable 'old_line' referenced before assignment
```

**Comment by dwrolvink** [comment]
You seem to be on a pretty old version of obsidianhtml. Could you run `obsidianhtml version` and then upgrade?

**Comment by MShields1986** [comment]
Rolled forward...
pip 22.3.1
obsidianhtml: 3.4.1

```bash
DEPRECATION WARNING: The setting obsidian_folder_path_str is deprecated. See https://obsidian-html.github.io/Configurations/Deprecated%20Configurations/Deprecated%20Configurations.html for more information.
> COPYING VAULT /home/matthew/Desktop/PhD/phd_notes/PhD TO /tmp/tmpo_yqafcu
running: 
	 rsync -a /home/matthew/Desktop/PhD/phd_notes/PhD/ /tmp/tmpo_yqafcu --exclude /.obsidian --exclude /.trash --exclude /.DS_Store --exclude /.git
Copy succeeded 0  b''
< COPYING VAULT: Done
> CLEARING OUTPUT FOLDERS
> CREATING OUTPUT FOLDERS
> COMPILING MARKDOWN FROM OBSIDIAN CODE (/tmp/tmpo_yqafcu/Home.md)
> COMPILING HTML FROM MARKDOWN CODE (/home/matthew/Desktop/PhD/phd_notes/output/md/index.md)
Traceback (most recent call last):
  File "/home/matthew/.local/lib/python3.9/site-packages/obsidianhtml/core/ErrorHandling.py", line 60, in _decorator
    res = f(*args, **kwargs)
  File "/home/matthew/.local/lib/python3.9/site-packages/obsidianhtml/controller/ConvertVault.py", line 859, in crawl_markdown_notes_and_convert_to_html
    html_body = markdown.markdown(md.page, extensions=extensions, extension_configs=extension_configs)
  File "/home/matthew/.local/lib/python3.9/site-packages/markdown/core.py", line 387, in markdown
    return md.convert(text)
  File "/home/matthew/.local/lib/python3.9/site-packages/markdown/core.py", line 261, in convert
    self.lines = prep.run(self.lines)
  File "/home/matthew/.local/lib/python3.9/site-packages/obsidianhtml/markdown_extensions/MermaidExtension.py", line 60, in run
    if not re.match(r"^[\ \t]*$", old_line):
UnboundLocalError: local variable 'old_line' referenced before assignment

	OBS.HTML EXTRA ERROR INFORMATION:
	---------------------------------
	Current action              : Conversion of markdown notes to html notes
	Subroutine                  : crawl_markdown_notes_and_convert_to_html
	Current note being processed: /home/matthew/Desktop/PhD/phd_notes/output/md/Starter Information/Departmental Org Chart.md ()
```

**Comment by mpolushkin** [comment]
I just ran into this problem as well using version 3.4.1. Changing `old_line` to `line` in `MermaidExtension.py`, line 60, seems to fix it for me, and results in the expected output. I didn't look too deeply into the code to understand if that breaks anything else.

**Comment by dwrolvink** [comment]
Managed to replicate this error by having a note that starts with a mermaid diagram.

Your fix will work in the current context, I made a slightly different fix, which I just merged.
