### ISSUE TITLE
AttributeError: 'str' object has no attribute 'items'

### ISSUE THREAD

**Issue by mschnick** [obsidian-html/obsidian-html#568]
Error when converting with version 3.3.0.

command is called as 
`python3 ~/git/obsidian-html/obsidianhtml convert -i ~/ownCloud/obsidian/DSA/home.md`

Application bails out with the following stacktrace.

I'll attach the current vault content.

```
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Users/m.schnick/git/obsidian-html/obsidianhtml/__main__.py", line 3, in <module>
    main()
  File "/usr/local/lib/python3.10/site-packages/obsidianhtml/__init__.py", line 32, in main
    ConvertVault()
  File "/usr/local/lib/python3.10/site-packages/obsidianhtml/ConvertVault.py", line 79, in ConvertVault
    pb.loadConfig(input_yml_path_str)
  File "/usr/local/lib/python3.10/site-packages/obsidianhtml/PicknickBasket.py", line 45, in loadConfig
    self.config = Config(self, input_yml_path_str)
  File "/usr/local/lib/python3.10/site-packages/obsidianhtml/ConfigManager.py", line 35, in __init__
    self.config = MergeDictRecurse(default_config, input_config)
  File "/usr/local/lib/python3.10/site-packages/obsidianhtml/ConfigManager.py", line 191, in MergeDictRecurse
    for k, v in update_dict.items():
AttributeError: 'str' object has no attribute 'items'
```

**Comment by mschnick** [comment]
[DSA.zip](https://github.com/obsidian-html/obsidian-html/files/10530522/DSA.zip)

**Comment by dwrolvink** [comment]
You need to run either:
``` bash
obsidianhtml run -f ~/ownCloud/obsidian/DSA/home.md
``` 
Or

``` bash
obsidianhtml convert -i ~/path/to/config.yml
```

You are now passing in a markdown file as a yaml config file.

Btw, version 3.4.1 is out, might as well use that.
