### ISSUE TITLE
IMPORTANT: Moving to a Module system & Version 4

### ISSUE THREAD

**Issue by dwrolvink** [obsidian-html/obsidian-html#631]
Master branch now contains code that uses the new (in development) module system.
This change was combined with work for preparing version 4, so config.yml changes will be necessary to use this code.

Branch v3.5.x can be used for patches of the currently released version 3.5.0.

Read more: https://obsidian-html.github.io/log/moving-to-a-module-system.html

**Comment by Gewerd-Strauss** [comment]
Catching up with the new merges. 


---

How does one feed a config when debugging the utility now? 

Previously I used e.g.

    sys.argv.append("convert")
    sys.argv.append("- i")
    sys.argv.append("D:\Dokumente neu\000 AAA Dokumente\000 AAA HSRW\General\AHK scripts\Projects\Finished\ObsidianScripts\OHTMLconfig_temp.yaml")
    
in `\obsidianhtml\__init__.py` at lines 15ff.
    
This does not seem to be valid. 

Or rather, I am getting an error stating that `log_output_folder_path_str` is not a valid key. 
Problem is, the config I feed

    # Input and output path of markdown files
    # This can be an absolute or a relative path (relative to the working directory when calling obsidianhtml)
    # Use full path or relative path, but don't use ~/
    # md_folder_path_str:  'output/md'
    # Number of links a note can be removed from the entrypoint note
    # -1 for no max depth
    # 0 means only the entrypoint note is processed
    # 1 means only direct children are processed (and the entrypoint of course)
    # and so forth. NOTE: DOES NOT APPLY TO INCLUSIONS!
    obsidian_entrypoint_path_str: 'D:\Dokumente neu\Obsidian NoteTaking\The Universe\019-Bugtesting-Subvault\019-ObsHTML_EmbeddedTitleStripping_Main.md'
    max_note_depth: 15
    # preserve_inline_tags: False
    toggles:
    # When true, Obsidianhtml will not add three spaces at the end of every line
      strict_line_breaks: True
      compile_html: False
    
does not ever supply it. The problem is that for keys not supplied, shouldn't OHTML still use native defaults? In which case I am really confused. 

---

Additionally, I do not encounter the error if I run this via the command window, just if I use `sys.argv.append()`, but I also can't seem to run `obsidianhtml/parser/MarkdownPage.py` → `ConvertObsidianPageToMarkdownPage()` when running 6e67cce with the changes I outlined above. Dunno... Might be super stupid right now cuz I haven't had reasons to look into python for a couple weeks again, in which case I am sorry.


I am sorry if this is the wrong issue to post under, I am still getting a handle about things and could not find the most suitable issue/commit to post this under.

---

Moving to a new module system seems interesting for making modding like mine much easier to perform and reapply when attempting to update to remote instance. 
Are all updates since v.3.5.0 (or most specifically,  since f933deb) geared towards this eventual module-rewrite?  
In that case I would probably wait for that to be finished before attempting to implement my modifications.



I am pretty content with my local branch right now cuz I so far do not need anything but the `convert`-functionality, but I'd like to keep stuff up to date for the sake of eventually interesting-to-me updates nonetheless. The only file I have actually modded is `obsidianhtml/parser/MarkdownPage.py`, but without being able to debug it I don't feel confident in modding it again - or rather, it doesn't work, and I can't figure out why right now. 
The truely interesting thing for me is that future modding will be much more doable for me if this system is completely implemented (to my understanding this is not the case right now).

---

Thank you,  
Sincerely,  
~Gw

**Comment by dwrolvink** [comment]
I've applied this code to the latest master version where you said you put it:
![image](https://github.com/obsidian-html/obsidian-html/assets/30291690/81a49cd9-47c4-4c59-b953-ee3beb59b675)

And running  `python -m obsidianhtml` works for me.

Note that you provided `- i` instead of `-i`. Try changing that if you have the same error in your code.

Note that if you have obsidianhtml installed both via pip and via a git clone, then running `obsidianhtml` might run the pip installed version, and not use your custom files. Something to look out for.

----

> log_output_folder_path_str not a valid key

The logging output has been removed. The module system should write everything to the module_data_folder.
There is already quite a bit of logging to be found there as we speak.

> I am sorry if this is the wrong issue to post under, I am still getting a handle about things and could not find the most suitable issue/commit to post this under.

No worries. When in doubt, have a look also at https://github.com/obsidian-html/obsidian-html/discussions
That is a bit more freeform. Issues should preferably be very specific bugs/feature requests, with each issue being a single bug/request.

> Moving to a new module system seems interesting for making modding like mine much easier to perform and reapply when attempting to update to remote instance.

Indeed! It is pretty slow though, so I don't think this line can be continued all the way to the functions that execute foreach note, at least not unless I get the whole system to be a bit snappier.

If you want to try out version 4, I'd suggest making a test vault, and installing v4. You can always switch back to v3.5.x at any time. 
If you want to give a go at creating a custom module, have a look at this page: https://obsidian-html.github.io/v4/configurations/modules/developer-documentation/creating-a-custom-module.html (currently completely up to date :) )

> Are all updates since v.3.5.0 (or most specifically, since https://github.com/obsidian-html/obsidian-html/commit/f933deb96f65069fc24e0db0b2fa2cbc0be8bb2a) geared towards this eventual module-rewrite?
In that case I would probably wait for that to be finished before attempting to implement my modifications.

Any severe bugs found in the latest published version (3.5.2 as we speak) are applied to both the 3.5.x and the master branches. Other than that, currently I am working on updating the documentation for v4, furthering the module system, and removing deprecated config/options/etc. 

Any enhancements will only be applied to v4 (master) so I can only recommend you to switch over anyways. The module system is pretty much fleshed out by now, at least the configuration part of it, and most of the deprecated keys have been removed, so switching over now should be as good a time as any as far as I can tell atm.

I am currently planning on completely removing `obsidianhtml run` in favor of a more extensive `obsidianhtml convert`. I've also added a first version of `obsidianhtml config`, with which it should be possible to define aliases for config files, which is mostly useful for if you have a lot of different vaults/subvaults/etc. But I guess that is a niche issue that mostly applies to me because of all the testing with user's vaults.

Just to give you an idea what to expect for version 4.

**Comment by Gewerd-Strauss** [comment]
> The logging output has been removed. The module system should write everything to the module_data_folder.
There is already quite a bit of logging to be found there as we speak.

I seem to be utterly unable to locate said folder, or any folder containing the string `_data`, for that matter. I might be dumb though.

---

It seems to work again on th now, with all of _nothing_ changed... so yea. I am still suspicious because I'd rather have it not work at all than mysteriously work some of the time, but as long as it does work I won't complain.
> `- i`

Fixed, but wasn't at fault - or it was in some silently failing way I am too inexperienced to recognise ¯\\\_(ツ)_/¯.

> I am currently planning on completely removing obsidianhtml run in favor of a more extensive obsidianhtml convert

Out of curiosity, what's the feature additions you want to add to `convert`? `Run` has been basically deprecated for me as I never need the hosting - now done by `serve`, but I am curious what the plan is for those.

Initially, attempting to simply implement just and only this change, would cause issues for unknown reasons:

https://github.com/Gewerd-Strauss/obsidian-html/commit/f325645686b4a76d42d387fb08032fba0d211022

traceback:

```python
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "D:\Dokumente neu\ObsidianPluginDev\obsidian-html\obsidianhtml\__main__.py", line 3, in <module>
    main()
  File "D:\Dokumente neu\ObsidianPluginDev\obsidian-html\obsidianhtml\__init__.py", line 30, in main
    ConvertVault()
  File "D:\Dokumente neu\ObsidianPluginDev\obsidian-html\obsidianhtml\controller\ConvertVault.py", line 68, in ConvertVault
    run_module(module_listing)
  File "D:\Dokumente neu\ObsidianPluginDev\obsidian-html\obsidianhtml\controller\ConvertVault.py", line 58, in run_module
    module_controller.run_module(
  File "D:\Dokumente neu\ObsidianPluginDev\obsidian-html\obsidianhtml\modules\controller.py", line 79, in run_module
    result = module_dot_method()
             ^^^^^^^^^^^^^^^^^^^
  File "D:\Dokumente neu\ObsidianPluginDev\obsidian-html\obsidianhtml\modules\builtin\html_templater.py", line 40, in run
    self.get_html_template()
  File "D:\Dokumente neu\ObsidianPluginDev\obsidian-html\obsidianhtml\modules\builtin\html_templater.py", line 48, in get_html_template
    self.modfile("note.template.html", "").write()
  File "D:\Dokumente neu\ObsidianPluginDev\obsidian-html\obsidianhtml\modules\handlers\file.py", line 81, in write
    raise Exception(
Exception: ModuleMisConfiguration: Module html_templater writes to note.template.html but this is not reported in self.provides.
```

I didn't see how either of those modifications would cause an issue in the these code sections, so I was utterly spooked and started digging. 
I finally hunted it down to an issue with having provided `compile_html: False` as a toggle in my config file. This is odd however, because both the v4-documentation and the default config given by v4 will still populate this toggle with `True` - which _should_ speed up the processing time significantly if I am correctly informed. 

For me, this is either an ambiguous bug or something I _really_ do not understand the reason for. I would prefer clarification on this, as the [v4 docs](https://obsidian-html.github.io/v4/configurations/configuration-options.html#!toggles_1) still list it as valid.


---

> No worries. When in doubt, have a look also at https://github.com/obsidian-html/obsidian-html/discussions
That is a bit more freeform. Issues should preferably be very specific bugs/feature requests, with each issue being a single bug/request.

Will keep this in mind for the future, thank you.

**Comment by Gewerd-Strauss** [comment]
> Any enhancements will only be applied to v4 (master)

I'd suggest that running `(python -m ) obsidianhtml version` on the main branch should not print 3.5.0, but something along the lines of 4.0.0, or 4.0.0-alpha or similar, along the specific commit ID - to make distinguishing between the branches faster than remembering commit IDs. As it seems like main is destined to be the permanent place for v4 this would make sense going forward.

**Comment by dwrolvink** [comment]
> I seem to be utterly unable to locate said folder, or any folder containing the string _data, for that matter.

https://github.com/obsidian-html/obsidian-html/blob/17c42eb4738339395e3650c4a6d9f128df0566c8/obsidianhtml/src/defaults_config.yml#L33

---

> It seems to work again on th now, with all of nothing changed... so yea.

Might be dependent on the location that you run commands from. For example, if you clone this project under /home/gewerd/git/obsidian-html, then running `python -m obsidianhtml` will use this project, as there is the folder `obsidianhtml` in the gitroot. When you are elsewhere on your system:

![image](https://github.com/obsidian-html/obsidian-html/assets/30291690/5a4f485b-96ce-4edb-86be-4a866e4104d4)

---

> Out of curiosity, what's the feature additions you want to add to convert? Run has been basically deprecated for me as I never need the hosting - now done by serve, but I am curious what the plan is for those.

I was working on adding the `--subfolder` command, and I've already added a default fallback, so if you don't pass in a config file it will look at the default location and get the config file from there. Run also was exclusive in being able to figure out the correct vault folder location from only giving it the entrypoint path, but that has already been ported to convert some time back. Mostly toggles to overwrite the passed in config in a foolproof way, for settings where I see users make problems often.

But I really have to think it through a bit more instead of building something haphazardly again that turns out to be counterproductive.

For example the "getting the config file from the default location if no config file is passed in" is also kind of a foot gun that I should probably remove before release, as in your case of `- i`, it doesn't catch that at the moment, and it will default to the default location, which you might not be aware of.

---

> https://github.com/Gewerd-Strauss/obsidian-html/commit/f325645686b4a76d42d387fb08032fba0d211022

This change itself should not create that error. I looked at the master branch that that commit points to, but there is no `modules` folder, and your master branch is 93 commits behind the master branch of this project. So that is a bit confusing for me. I found the error though, and it is mine.

This error is an internal error meant for the module developer (me) that a `self.modfile(<path>).write()` was not declared.
In `D:\Dokumente neu\ObsidianPluginDev\obsidian-html\obsidianhtml\modules\builtin\html_templater.py` you should see this block:

``` python
    @property
    def provides(self):
        return tuple(
            [
                "html/note.template.html",
                "html/dynamic_inclusions.html",
                "html/dynamic_footer_inclusions.html",
            ]
        )
```

And in the line of the error, 48-ish, you see this:
``` python
        # write empty file that we promised to provide and exit, if html is not compiled
        if gc("toggles/compile_html") == False:
            self.modfile("note.template.html", "").write()
            return
```

`self.modfile("note.template.html", "").write()` should have been changed to `self.modfile("html/note.template.html", "").write()` but I missed that one. Fixed it just now.

----

> I'd suggest that running (python -m ) obsidianhtml version on the main branch should not print 3.5.0, but something along the lines of 4.0.0, or 4.0.0-alpha

4.0.0-alpha is a good idea!
I had written a script to keep this updated, but committing via the vscode git plugin is just so darn convenient, which I use for everything else, that I keep forgetting. I could setup a pipeline to edit it for me always, but that would give its own issues with merging back changes probably.

Will edit the version locally, it will be pulled in on next PR!

Cheers!

**Comment by Gewerd-Strauss** [comment]
> your master branch is 93 commits behind the master branch of this project. So that is a bit confusing for me.


Yea that's admittedly odd for outstanders. Because I am on the war-path with git when it comes to certain things, and one of them is the question of `how to pull remote commits onto a local branch that has a single differing commit (my modifications) without annihilating the history` and because this project updates so quickly, I usually don't push my mods - I did it once, then regretted it basically immediately. I now have my relevant mods just stashed and reapply them whenever I pull the remotes.  However, as a side effect there is no actual commit that contains the modifications I use - which is fine for this kind of rapid development, but is stupid once you'd merge stuff back into a master. Just... haven't found a solution to it yet. 

You might have noticed, while I know some git, I am by no means an expert.

> I seem to be utterly unable to locate said folder, or any folder containing the string _data, for that matter.
>
> \+ your answer, no clue how to quote that in markdown :P

Ooooh... yea no wonder I wasn't able to find that folder, because my script autocleans the output directory ...



Whew, that's... a lot of info dumped. Probably useful for myself too, it will take some time for me to see if there is anything valuable in there.


---


>   committing via the vscode git plugin is just so darn convenient

Well, I'd disagree, but great if it works for you.

I work way too all-over-the-place for me to do one feature, commit it, and do the next. I rather solve 20 issues and add 5 small adjustments over 2 hours, then sit back and commit it line by line on a per-usecase basis :P

---


Aside from that there are a couple of errors I am encountering yet again on all branches that I will hunt down over the course of the next couple of days to see what's going on before opening relevant issues.

Most regular one I am encountering is seeminly related to unicode strings in the yaml parsing of `parse_metadata.py`, but I couldn't narrow down the infringing file so far - my vault is large, has a lot of components and a lot of files stuck in different eras of method-development - it probably has enough unforseen pseudo-edge cases for me to open issues until I'm dead :P
