### ISSUE TITLE
File not found error when Index.md exists but is not the entrypoint

### ISSUE THREAD

**Issue by dwrolvink** [obsidian-html/obsidian-html#683]
File not found error occurs when:
- A file exists in the root of the vault called `Index.md`
- The entrypoint is NOT that file

Renaming the file to either `_Index.md` or `index.md` fixes this.

- Possibly caused by key overlap (both `index.md` and `Index.md` wanting to use the same key, causing confusion)
- Probably caused by the `.lower()` mechanism in the slugify/lowercase filenames features.

```
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/dorus/git/obsidian-html/obsidianhtml/__main__.py", line 3, in <module>
    main()
  File "/home/dorus/git/obsidian-html/obsidianhtml/__init__.py", line 30, in main
    ConvertVault()
  File "/home/dorus/git/obsidian-html/obsidianhtml/controller/ConvertVault.py", line 81, in ConvertVault
    convert_markdown_to_html(pb)
  File "/home/dorus/git/obsidian-html/obsidianhtml/controller/ConvertVault.py", line 175, in convert_markdown_to_html
    crawl_markdown_notes_and_convert_to_html(entrypoint_file_object, pb)
  File "/home/dorus/git/obsidian-html/obsidianhtml/controller/ConvertVault.py", line 549, in crawl_markdown_notes_and_convert_to_html
    node, md_links = md2html.convert_markdown_page_to_html_and_export(fo, pb, backlink_node, log_level, capture_in_jar)
  File "/home/dorus/git/obsidian-html/obsidianhtml/md2html/__init__.py", line 46, in convert_markdown_page_to_html_and_export
    md = fo.load_markdown_page("markdown")
  File "/home/dorus/git/obsidian-html/obsidianhtml/core/FileObject.py", line 61, in load_markdown_page
    self.md = MarkdownPage(self, input_type)
  File "/home/dorus/git/obsidian-html/obsidianhtml/parser/MarkdownPage.py", line 44, in __init__
    with open(self.src_path, encoding="utf-8") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/dorus/git/obsidian-html/output/md/Index.md'
```

**Comment by dwrolvink** [comment]
After reviewing what would be needed to get this to work, it is clear that the whole structure of the program would need to be redone to have this not be an issue. Not really worth it for a niche issue.

See also:
- https://obsidian-html.github.io/v4/general-information/common-issues-limitations.html#!you-can-t-have-a-note-named-index-index-in-the-root-of-your-vault-if-it-is-not-the-entrypoint
