### ISSUE TITLE
filter_on_metadata not working

### ISSUE THREAD

**Issue by cquenelle** [obsidian-html/obsidian-html#731]
I added this to the config file:
```module_config:
  filter_on_metadata:
    include_on: [[ {'tagged': 'publish'} ]]
    exclude_on: [[ ]]
```

And I got this backtrace (start omitted)
```  File "/Users/cquenell/miniforge3/envs/e39/lib/python3.9/site-packages/obsidianhtml/modules/controller.py", line 224, in instantiate_module
    module_obj = module_class(module_data_folder=module_data_folder, module_name=module_name, persistent=persistent)
  File "/Users/cquenell/miniforge3/envs/e39/lib/python3.9/site-packages/obsidianhtml/modules/base_classes/obsidianhtml_module.py", line 58, in __init__
    self.try_load_mod_config()
  File "/Users/cquenell/miniforge3/envs/e39/lib/python3.9/site-packages/obsidianhtml/modules/base_classes/obsidianhtml_module.py", line 86, in try_load_mod_config
    self.mod_config[key]["value"] = item["value"]
TypeError: list indices must be integers or slices, not str
```

This is using code pip installed from here:
```
commit 821cadb4cf3e2cfb533fcb7bcdfe480e9e5fab06 (HEAD -> master)
Merge: 11d1836 fe14599
Author: Dorus <30291690+dwrolvink@users.noreply.github.com>
Date:   Wed May 10 15:09:00 2023 +0200

    Merge pull request #641 from dwrolvink/master
    
    misc

```

**Comment by dwrolvink** [comment]
Woops, I changed the config structure of the modules, but never updated this part of it.

I also noticed while replicating your issue, an issue with the empty exclude list always returning true for exclude, not sure how that snuck in there after having tested it.

Try fetching the latest changes in master and changing your config to this:
``` yaml
  filter_on_metadata:
    include_on: 
      description: What metadata to include notes on. Empty list means True by default.
      value: [[]]
    exclude_on: 
      description: What metadata to exclude on. Empty list means False by default
      value: [[]]
```

Updated the docs:
- https://obsidian-html.github.io/v4/configurations/modules/filter-on-metadata.html

**Comment by cquenelle** [comment]
Still fails.  New stacktrace:
```
Traceback (most recent call last):
  File "/Users/cquenell/miniforge3/envs/e39/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/cquenell/miniforge3/envs/e39/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/cquenell/miniforge3/envs/e39/lib/python3.9/site-packages/obsidianhtml/__main__.py", line 3, in <module>
    main()
  File "/Users/cquenell/miniforge3/envs/e39/lib/python3.9/site-packages/obsidianhtml/__init__.py", line 30, in main
    ConvertVault()
  File "/Users/cquenell/miniforge3/envs/e39/lib/python3.9/site-packages/obsidianhtml/controller/ConvertVault.py", line 68, in ConvertVault
    run_module(module_listing)
  File "/Users/cquenell/miniforge3/envs/e39/lib/python3.9/site-packages/obsidianhtml/controller/ConvertVault.py", line 57, in run_module
    module_controller.run_module(
  File "/Users/cquenell/miniforge3/envs/e39/lib/python3.9/site-packages/obsidianhtml/modules/controller.py", line 82, in run_module
    result = module_dot_method()
  File "/Users/cquenell/miniforge3/envs/e39/lib/python3.9/site-packages/obsidianhtml/modules/builtin/copy_vault_to_tempdirectory.py", line 87, in run
    files = self.modfile("index/files.json").read().from_json()
  File "/Users/cquenell/miniforge3/envs/e39/lib/python3.9/site-packages/obsidianhtml/modules/handlers/file.py", line 63, in read
    raise Exception(
```

Attached my latest config file.  I turned on a few unnecessary things to try to get it to work
[newconfigcopy.yaml.txt](https://github.com/obsidian-html/obsidian-html/files/11620922/newconfigcopy.yaml.txt)

**Comment by cquenelle** [comment]
I am thinking that in module_list / preparation:
get_file_list should come before copy_vault_to_tempdirectory
ahhh I see the default config file changed.  I didn't update my own.
I'm getting farther now

**Comment by dwrolvink** [comment]
Yes that is still something I'm not sure how to solve.
To add in modules you need to copy the whole module_list config, but if that ever changes and people have overwritten it then they don't get the updates.

Perhaps using a priority number like in python-markdown would work better, but I'm not sure yet.
Would need to be something where the order of modules is clear and visible, but easy to edit in a user config...

**Comment by cquenelle** [comment]
I got it working, so I'll close this issue.
