### ISSUE TITLE
re.escape(node_id) gives KeyError: '\\E'

### ISSUE THREAD

**Issue by dwrolvink** [obsidian-html/obsidian-html#85]
Testing on Windows led me to this strange error:

When running `re.escape(node_id)` with `node_id = "index" (first occurrence), it gives me this error:

```
Traceback (most recent call last):
  File "C:\Users\dwrol\AppData\Local\Programs\Python\Python39\lib\sre_parse.py", line 1039, in parse_template
    this = chr(ESCAPES[this][1])
KeyError: '\\E'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dwrol\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\dwrol\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\dwrol\git\obsidian-html\obsidianhtml\__main__.py", line 3, in <module>
    main()
  File "C:\Users\dwrol\git\obsidian-html\obsidianhtml\__init__.py", line 769, in main
    html = re.sub('\{_obsidian_html_backlinks_pattern_:'+re.escape(node_id)+'}', snippet, html)
  File "C:\Users\dwrol\AppData\Local\Programs\Python\Python39\lib\re.py", line 210, in sub
    return _compile(pattern, flags).sub(repl, string, count)
  File "C:\Users\dwrol\AppData\Local\Programs\Python\Python39\lib\re.py", line 327, in _subx
    template = _compile_repl(template, pattern)
  File "C:\Users\dwrol\AppData\Local\Programs\Python\Python39\lib\re.py", line 318, in _compile_repl
    return sre_parse.parse_template(repl, pattern)
  File "C:\Users\dwrol\AppData\Local\Programs\Python\Python39\lib\sre_parse.py", line 1042, in parse_template
    raise s.error('bad escape %s' % this, len(this))
re.error: bad escape \E at position 48 (line 3, column 25)
```

This is resolved by changing
``` python
import re
```

to 

``` python
import regex as re
```

Not sure yet why this works, and if it will break linux.
Will investigate more.

**Comment by dwrolvink** [comment]
Not clear what the difference is between the packages regex and re, but regex as a replacement works and passes all the tests and resolves this issue on Windows, so I'll go with that one.
