### ISSUE TITLE
running unit test, get an error on linux and osx ... not sure if it's just because char count is invalid?

### ISSUE THREAD

**Issue by jcolson** [obsidian-html/obsidian-html#99]
```
======================================================================
FAIL: test_special_characters_should_be_preserved (__main__.TestMisc)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/obsidian-html/ci/tests/basic_regression_test.py", line 265, in test_special_characters_should_be_preserved
    self.assertIn(len(soup.text), {20925, 20926}, msg="difference in length means that characters have been lost")
AssertionError: 21064 not found in {20925, 20926} : difference in length means that characters have been lost

----------------------------------------------------------------------
Ran 8 tests in 0.649s

FAILED (failures=1)
DEFERRED: closed webserver
root@36cbb04aaa95:/obsidian-html# uname -a
Linux 36cbb04aaa95 5.10.76-linuxkit #1 SMP PREEMPT Mon Nov 8 11:22:26 UTC 2021 aarch64 GNU/Linux
```

and

```
======================================================================
FAIL: test_special_characters_should_be_preserved (__main__.TestMisc)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/jcolson/src/opensource/obsidian-html/ci/tests/basic_regression_test.py", line 265, in test_special_characters_should_be_preserved
    self.assertIn(len(soup.text), {20925, 20926}, msg="difference in length means that characters have been lost")
AssertionError: 21064 not found in {20925, 20926} : difference in length means that characters have been lost

----------------------------------------------------------------------
Ran 8 tests in 1.005s

FAILED (failures=1)
DEFERRED: closed webserver
jcolson▶jay-m1▶jmaster▶1✎▶1+▶1s▶~▶src❯opensource❯obsidian-html▶1▶$▶ uname -a
Darwin jay-m1.lan 21.3.0 Darwin Kernel Version 21.3.0: Wed Jan  5 21:37:58 PST 2022; root:xnu-8019.80.24~20/RELEASE_ARM64_T8101 arm64
```

**Comment by dwrolvink** [comment]
Not sure why this happened, nothing changed that should affect the line count as far as I can tell.
But I just checked, and the special characters are still present. 

Might change the test soon to check for presence of the chars, instead of number of chars in the entire document, not very stable of a test 

Fixed in #105
